#THIS PYTHON FILE SHOW THE DATA ANALYSIS OF THE SALES DATA

In [1]:
import pandas as pd

#loading of the data and basic information of the data

In [2]:
data = pd.read_csv('data.csv') 
# load of the data
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      50 non-null     object
 1   Category  50 non-null     object
 2   Value     47 non-null     float64
 3   Product   50 non-null     object
 4   Sales     46 non-null     float64
 5   Region    50 non-null     object
dtypes: float64(2), object(4)
memory usage: 2.5+ KB
None

In [4]:
print(data.describe()) # for understanding the statistics of the data

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

Question 1: Basic Data Cleaning
In real-world data analysis, the very first step is almost always handling messy or missing data 
Task:

Write the code to load the data.csv file.

Write the code to find out exactly how many missing values are in each column.

Write the code to fill the missing values in the Sales column with the mean (average) of that column.

# BASIC 
#Q1  loading of the data has been earlier refer to cell 3 

# q2 find out the missing values in each column 
missingvalues = data.copy()

In [3]:
missingvalues = data.copy()
print("missing values in the data")
missingvalues.isnull().sum(axis=0)

missing values in the data

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [12]:
missingvalues.head(6)

         Date Category  Value   Product  Sales Region
0  01-01-2023        A   28.0  Product1  754.0   East
1  02-01-2023        B   39.0  Product3  110.0  North
2  03-01-2023        C   32.0  Product2  398.0   East
3  04-01-2023        B    8.0  Product1  522.0   East
4  05-01-2023        B   26.0  Product3  869.0  North
5  06-01-2023        B   54.0  Product3  192.0   West

In [ ]:
missingvalues['Sales'].fillna(missingvalues['Sales'].mean(), inplace=True)

# or we can also do this by using assiging same column to itself
missingvalues['Sales'] = missingvalues['Sales'].fillna(missingvalues['Sales'].mean())

Question 2: Mid-Level Aggregation
Now that your data is clean (let's assume we saved it as a DataFrame called df_clean), your Sales Manager has come to your desk with a few questions about performance.

This will test your ability to use .groupby() and the .agg() dictionary method we talked about earlier!

Your Task:


Write the code to group the data by Region, and find the Total (sum) of the Sales for each region.

Write the code to group the data by Product, and use the .agg() function to find two things at once:

The Average (mean) of the Value column.

The Maximum (max) of the Sales column.

In [15]:
# q1 
aggregateddata = missingvalues.groupby("Region")["Sales"].sum()
print("SUM OF THE SALES IN EACH REGION")
print(aggregateddata)

SUM OF THE SALES IN EACH REGION
Region
East     7574.130435
North    6565.130435
South    5158.000000
West     8559.260870
Name: Sales, dtype: float64

# THERE ARE TWO WAY OF DOING IT FOLLOWING IT IS -  >

In [ ]:
# syntax 
# dataframe.groupby().agg({"column1":"function1","column2":"function2"})
# in the agg function we can also give the name to the new column by using 
# dataframe.groupby().agg( NEWCOLUMN1 = ("column1","function1"), NEWCOLUMN2 = ("column2","function2") )

In [ ]:
missingvalues.groupby("Product").agg( MEANVALUES=("Value","mean"), MAXSALES=("Sales","max"))

          MEANVALUES  MAXSALES
Product
Product1   46.214286     938.0
Product2   52.800000     992.0
Product3   55.166667     949.0

In [ ]:
#q2 
productanalysis = missingvalues[["Value","Sales","Product"]]
print(productanalysis.head(6))
# 
print(productanalysis.groupby("Product")["Sales"].mean()) # for checking the total sales are same 
print(productanalysis.groupby("Product")["Value"].max())
productanalysis.groupby("Product").agg({"Value":"mean","Sales":"max"}).rename(columns={"Value":"MEANVALUE","Sales":"MAXSALES"})

   Value  Sales   Product
0   28.0  754.0  Product1
1   39.0  110.0  Product3
2   32.0  398.0  Product2
3    8.0  522.0  Product1
4   26.0  869.0  Product3
5   54.0  192.0  Product3
Product
Product1    573.758152
Product2    565.884058
Product3    536.217391
Name: Sales, dtype: float64
Product
Product1    97.0
Product2    99.0
Product3    96.0
Name: Value, dtype: float64

          MEANVALUE  MAXSALES
Product
Product1  46.214286     938.0
Product2  52.800000     992.0
Product3  55.166667     949.0

Question 3: Filtering & Subsetting (Mid-Level)
Now that you have mastered grouping and aggregating, Manager has come back with a new request. They don't want a summary table; they want to see the actual raw data, but only for the best-performing records in a specific location.

Your Task:

Write the code to filter the missingvalues DataFrame to only show rows where the Sales are greater than 600.

Bonus Challenge: Write the code to filter the DataFrame where Sales are greater than 600 AND the Region is exactly "East".

Print the number of rows (the length) of this final filtered DataFrame so the manager knows how many records met both criteria.

In [4]:
#q1
greater =data.copy()
greater

greater600= greater[greater["Sales"] <600]

In [5]:
bonus = greater600[(greater600["Sales"]<600)&(greater600["Region"]=="East")]

In [6]:
noof= len(bonus)
print("number of sales greater than 600 in east region is",noof)

number of sales greater than 600 in east region is 7

In [30]:
# for checking the number of the non null values in the dataframe

numberzero = data["Sales"].isna().sum()
print("number of non null values in the sales column is",numberzero)
print(type(numberzero))

# as we are using the greater as it the copy of the data 

zero = greater[greater["Sales"].isna()]

print("NULL VALUES IN THE SALES COLUMN")
print(zero)

number of non null values in the sales column is 4
<class 'numpy.int64'>
NULL VALUES IN THE SALES COLUMN
          Date Category  Value   Product  Sales Region
11  12-01-2023        B   60.0  Product2    NaN   West
33  03-02-2023        C   27.0  Product3    NaN   East
35  05-02-2023        B   60.0  Product2    NaN   West
37  07-02-2023        C    2.0  Product1    NaN  North

In [7]:
#  for checking the len of the we can also use the shape function
print(bonus.shape[0])

7

Question 4: Feature Engineering & Sorting (Mid-Level)
The Sales Manager is thrilled with your data pulls. Now, they want to do some actual performance analysis. Sometimes the data we need doesn't exist yet, so we have to invent it using the data we already have! This is called Feature Engineering.

Assume we are back to using our clean DataFrame (let's call it data). Let's assume the Value column actually represents the "Number of Units Sold."

Your Task:

Create a New Column: Write the code to create a brand new column in your DataFrame called Price_Per_Unit. This should be calculated by dividing the Sales column by the Value column.

Sort the Data: Write the code to sort the entire DataFrame by this new Price_Per_Unit column in descending order (meaning the highest price should be at the very top).

Show the Leaders: Write the code to display only the top 5 rows of this newly sorted DataFrame.

In [10]:
# task four 
#creating a new column here
df=data.copy()
df["Price_Per_Unit"]=df["Sales"]/df["Value"]
print(df.head(6))

df.sort_values(by="Price_Per_Unit",ascending=False).head(5)

         Date Category  Value   Product  Sales Region  Price_Per_Unit
0  01-01-2023        A   28.0  Product1  754.0   East       26.928571
1  02-01-2023        B   39.0  Product3  110.0  North        2.820513
2  03-01-2023        C   32.0  Product2  398.0   East       12.437500
3  04-01-2023        B    8.0  Product1  522.0   East       65.250000
4  05-01-2023        B   26.0  Product3  869.0  North       33.423077
5  06-01-2023        B   54.0  Product3  192.0   West        3.555556

          Date Category  Value   Product  Sales Region  Price_Per_Unit
46  16-02-2023        B    6.0  Product1  938.0  South      156.333333
10  11-01-2023        B    7.0  Product1  842.0  North      120.285714
3   04-01-2023        B    8.0  Product1  522.0   East       65.250000
49  19-02-2023        C   11.0  Product3  708.0  North       64.363636
6   07-01-2023        A   16.0  Product1  936.0   East       58.500000